# Generated by Django 5.2.4 on 2025-09-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_create', 'Can Create'), ('can_delete', 'Can Delete'), ('can_edit', 'Can Edit'), ('can_view', 'Can View')]},
        ),
    ]
